name: solar system workflow

on:
  workflow_dispatch: 
  push:
    branches:
        - main
        - 'feature/*'
        
env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: unit testing
        runs-on: ubuntu-latest
        steps:
        - name: chekout Repository
          uses: actions/checkout@v4
        
        - name: setup Nodejs version - 18
          uses: actions/setup-node@v3
          with:
            node version: 18

        - name: install dependancy
          run: npm install

        - name: unit testing
          run: npm test

        - name: archive test result
          uses: actions/upload-artifact@v3
          with:
            name: mocha-Test-Result
            path: test-results.xml
    
